export const actionTypes = {
    //admin
    SET_ADMIN: "SET_ADMIN",
    REMOVE_ADMIN: "REMOVE_ADMIN",
    // user
    SET_USERLIST: "SET_USERLIST",
    SET_USER_EDIT: "SET_USER_EDIT",
    SET_OPEN: "SET_OPEN",
    SET_EDIT: "SET_EDIT",
    SET_PAGE: "SET_PAGE",
    // sidebar
    SET_SIDEBAR: "SET_SIDEBAR",
    SET_SIDEBAR_PAGE: "SET_SIDEBAR_PAGE",
    // movie
    SET_MOVIELIST: "SET_MOVIELIST",
    SET_PAGE_MOVIE: "SET_PAGE_MOVIE",
    SET_OPEN_PAGEMOVIE: "SET_OPEN_PAGEMOVIE",
    SET_EDIT_PAGEMOVIE: "SET_EDIT_PAGEMOVIE",
    SET_MOVIE_EDIT: "SET_MOVIE_EDIT",
    //cinema
    SET_CINEMA_SYSTEM: "SET_CINEMA_SYSTEM",
    SET_CINEMA_CLUSTER: "SET_CINEMA_CLUSTER",
};
