export const actionTypes = {
    //admin
    SET_ADMIN: "SET_ADMIN",
    SET_OPEN: "SET_OPEN",
    SET_EDIT: "SET_EDIT",
    SET_PAGE: "SET_PAGE",
    REMOVE_ADMIN: "REMOVE_ADMIN",
    // user
    SET_USERLIST: "SET_USERLIST",
    SET_USER_EDIT: "SET_USER_EDIT",
    // sidebar
    SET_SIDEBAR: "SET_SIDEBAR",
    // movie
    SET_MOVIELIST: "SET_MOVIELIST",
    SET_PAGE_MOVIE: "SET_PAGE_MOVIE",
    SET_OPEN_PAGEMOVIE: "SET_OPEN_PAGEMOVIE",
    SET_EDIT_PAGEMOVIE: "SET_EDIT_PAGEMOVIE",
    SET_MOIVE_EDIT: "SET_MOIVE_EDIT",
};
